baseURL = "https://swem.github.io/"
theme = "hyde-y"
languageCode = "en-us"
title = "ChenHan's Tech blog"
paginate = 10

[taxonomies]
    tag = "tags"

[params]
    # You can use markdown here.
    brand = "Chen-Han (Stanley) Hsiao"
    topline = "ChenHan's Tech blog"
    footline = ""

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"


    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Sidebar social links.
    github = "swem" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "chen-han-hsiao-2b486049" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid
    flickr = "" # Your Flickr profile ID
    vimeo = "" # Your Vimeo profile ID

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
