baseURL = "https://swem.github.io/"
theme = "hyde-x"
languageCode = "en-us"
title = "ChenHan's Tech blog"
paginate = 10

[taxonomies]
    # Optional. Use if you want tags and lists.
    tags = "tags"
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = false

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-08"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Chen-Han (Stanley) Hsiao"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/swem"
    bitbucket = ""
    stackOverflow = ""
    linkedin = "https://www.linkedin.com/in/chen-han-hsiao-2b486049"
    googleplus = ""
    facebook = ""
    twitter = ""
    youtube = ""
